### ISSUE TITLE
Mexican Spanish (Español Mexicano) <es-mx.cfg>

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/NotSoSimpleConstruction#21]
# Localization - ![Mexicano][ME] Mexican Spanish (Español Mexicano) <es-mx.cfg>

## GitHub

* [x] assign
  * [x] zer0Kerbal
  * [x] Repo Localization Project
  * [x] Label: type: localization
  * [x] Label: help-wanted
  * [x] Milestone: Localization - Master

### GameData

* [x] add  Localization\[es-mx.cfg] 🗃️

### Translation

* [x] ![Mexicano][ME] Mexican Spanish (Español Mexicano) <es-mx.cfg>

### Documentation

* [x] Update [readme.md] 🔢
* [x] Update [release.md] 🧾

### Wiki

* [x] Update docs/[localization.md]

## Update Social Media

* [x] GitHub (automated) (zer0Kerbal/zer0Kerbal)
* [x] CurseForge
* [x] Reddit
* [x] Twitter @zer0Kerbal
* [x] Forum
* [ ] Patreon
* [x] SpaceDock
* [x] CKAN (automated)

[URL:lclztn]: https://github.com/zer0Kerbal/lclztn/blob/master/readme.md "Localization"
[URL:qs]: https://github.com/zer0Kerbal/lclztn/blob/master/quickstart.md "Quick Start"

[ME]: https://raw.githubusercontent.com/zer0Kerbal/zer0Kerbal/zed'K/Localization/img/Mexican-flag-sm.png "Español Mexicano"

**Comment by AtomikkuSan** [comment]
Already working on it!

**Comment by AtomikkuSan** [comment]
https://github.com/zer0Kerbal/NotSoSimpleConstruction/pull/54

**Comment by zer0Kerbal** [comment]
I really need to switch back to hub instead of gh cli for publishing these issues - hub doesn't muck up the iso characters like gh cli does.

**Comment by zer0Kerbal** [comment]
constructive information:
![Screen_Recorder74070_9HvHb6R7ZD](https://user-images.githubusercontent.com/39887717/164069495-6f78e9ee-0e69-4537-8fcb-d121c353b38b.png)

**Comment by zer0Kerbal** [comment]
![image](https://user-images.githubusercontent.com/39887717/164069783-599f4b31-318e-4ccc-81e0-0a93063ad21f.png)

**Comment by zer0Kerbal** [comment]
![image](https://user-images.githubusercontent.com/39887717/164069858-2e391c44-9c26-428e-9ca4-92ac12d29478.png)

**Comment by AtomikkuSan** [comment]
Okay! Thanks for the heads-up!

I'm still not too great with the multiple branches thing with GitHub :P

**Comment by zer0Kerbal** [comment]
basic rule of thumb - try to not do anything on the master/main/release branch; everything should have an issue tied to a project, milestone, issue and pull request. 
also this might help:
https://github.com/jlord/git-it-electron (free)

**Comment by zer0Kerbal** [comment]
also:
https://www.atlassian.com/git
